---
# Source: aws-ebs-csi-driver/templates/controller/poddisruptionbudget.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ebs-csi-controller
  labels:
    app.kubernetes.io/name: aws-ebs-csi-driver
    app.kubernetes.io/component: controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-ebs-csi-driver
      app.kubernetes.io/component: controller
  maxUnavailable: 1
