---
# Source: aws-ebs-csi-driver/templates/node/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebs-csi-node-sa
  labels:
    app.kubernetes.io/name: aws-ebs-csi-driver
    app.kubernetes.io/component: node
