apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aws-ebs-csi-driver.controller.fullname" . }}
  labels:
    {{- include "aws-ebs-csi-driver.controller.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "aws-ebs-csi-driver.controller.selectorLabels" . | nindent 6 }}
  {{- if le (.Values.controller.replicaCount | int) 2 }}
  maxUnavailable: 1
  {{- else }}
  minAvailable: 2
  {{- end }}
