apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "aws-ebs-csi-driver.controller.fullname" . }}-leaderelection
  labels:
    {{- include "aws-ebs-csi-driver.controller.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "get", "watch", "list", "delete", "update", "create" ]